core_properties:
  bitbucket_parameters:
    import_directory: "import"
    objects_possible_to_upload: "Account,User"
credentials:
  Env1:
    server_url: "https://curious-koala-cek3d-dev-ed.my.salesforce.com"
    username: "teter.filip@curious-koala-cek3d.com"
    connapp_consumerkey_id: "connectedAppConsumerKey"
    cred_id: "e34e098b-73bb-4c92-aaa3-d1feb4f6cd66"
  Env2:
    server_url: "https://curious-koala-cek3d-dev-ed.my.salesforce.com"
    username: "teter.filip@curious-koala-cek3d.com"
    connapp_consumerkey_id: "connectedAppConsumerKey"
    cred_id: "e34e098b-73bb-4c92-aaa3-d1feb4f6cd66"
  Env3:
    server_url: "https://curious-koala-cek3d-dev-ed.my.salesforce.com"
    username: "teter.filip@curious-koala-cek3d.com"
    connapp_consumerkey_id: "connectedAppConsumerKey"
    cred_id: "e34e098b-73bb-4c92-aaa3-d1feb4f6cd66"