credentials:
  Env1:
    server_url: "https://curious-koala-cek3d-dev-ed.my.salesforce.com"
    username: "teter.filip@curious-koala-cek3d.com"
    connapp_consumerkey_id: "connectedAppConsumerKey"
    cred_id: "server.key"
  Env2:
    server_url: "https://curious-koala-cek3d-dev-ed.my.salesforce.com"
    username: "teter.filip@curious-koala-cek3d.com"
    connapp_consumerkey_id: "connectedAppConsumerKey"
    cred_id: "server.key"
  Env3:
    server_url: "https://curious-koala-cek3d-dev-ed.my.salesforce.com"
    username: "teter.filip@curious-koala-cek3d.com"
    connapp_consumerkey_id: "connectedAppConsumerKey"
    cred_id: "server.key"