core_properties:
  salesforce_parameters:
    objects_possible_to_upload: "Account,User"
  bitbucket_parameters:
    bitbucket_import_dir: "data"
    bitbucket_src_rep: "https://source.app.pconnect.biz/scm/esdp/esd-pmi-dx.git"
    bitbucket_cred_id: "ESDBitBucketTechnicalAccess"
    bitbucket_cred_mail: "Filip.Teter@contracted.pmi.com"
    bitbucket_cred_name: "fteter@PMINTL.NET"
credentials:
  Transla2:
    server_url: "https://test.salesforce.com"
    username: "transla2ftUsername"
    connapp_consumerkey_id: "transla2ConnectedAppInfo"
    cred_id: "serverKeyEsdDxSandbox"